"""Generate ``DATA_CARD.md`` from the build's own manifest.

    uv run python -m v6.data_card              # writes data/v6-corpus/DATA_CARD.md
    uv run python -m v6.data_card --stdout

Section 5 requires a data card covering sources, licences, attribution, PII
treatment and known limitations. Every number in it comes from
``MANIFEST.json`` and the collectors' configs rather than from prose, so
re-running the build refreshes the card instead of leaving it to drift. A
figure typed into a document is a figure that goes stale silently; that is
the same failure as a hand-maintained layer list, which is what left four
layers out of the manifest.

Prose that is a judgement rather than a measurement -- intended use, what the
corpus is not for, the limitations -- lives here, next to the code that
states the measurements, and cites DATASET_SPEC for the argument.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from .build_windows_corpus import OUT, attribution, source_license

CARD = OUT / "DATA_CARD.md"


def _fmt(n) -> str:
    return f"{n:,}" if isinstance(n, int) else str(n)


def render(m: dict) -> str:
    attrib = attribution()
    doms = m.get("domains", {})
    tot_w = sum(d.get("windows", 0) for d in doms.values())
    tot_t = sum(d.get("tokens", 0) for d in doms.values())
    tot_s = sum(d.get("sentences", 0) for d in doms.values())
    st = m.get("stats", {})

    L = []
    A = L.append
    A("# kniv v6 training corpus — data card")
    A("")
    A("Generated by `v6/data_card.py` from `MANIFEST.json`. Do not edit by "
      "hand: re-run the generator.")
    A("")
    A(f"- **Build**: git `{m.get('git_sha', 'unknown')}`")
    A(f"- **Windows**: {_fmt(tot_w)} · **sentences**: {_fmt(tot_s)} · "
      f"**tokens**: {_fmt(tot_t)}")
    A(f"- **Shards**: {m.get('shards', '?')}, laid out as "
      "`corpus/split=<split>/domain=<domain>/part-*.parquet`")
    A("")

    A("## What this is")
    A("")
    A("One multi-domain English corpus, annotated for every layer the kniv "
      "cascade predicts, so that a single model can be trained across layers "
      "instead of one model per task. The unit of a row is a **window** of at "
      "most 512 whitespace tokens that never crosses a document boundary and "
      "never splits a sentence.")
    A("")
    A("Structural layers (POS, lemma, morph, DEP, NER, SRL) are annotated "
      "**per sentence** inside the window and mapped back to window "
      "coordinates; only coreference and relations see the whole window. "
      "Feeding a whole window to a sentence-level model costs 43 points of "
      "agreement (DATASET_SPEC §4.1a), which is why `sentence_spans` is a "
      "first-class field.")
    A("")

    A("## Sources, licences and attribution")
    A("")
    A("Attribution is a requirement, not provenance decoration: CC-BY and "
      "CC-BY-SA material is present, so every row carries `source`, "
      "`source_url` and `license`. **If the dataset is published, "
      "share-alike terms apply to it.** The trained model is not a derivative "
      "work of its training data.")
    A("")
    A("| domain | windows | documents | tokens | sources | licences |")
    A("|---|---|---|---|---|---|")
    for d, v in sorted(doms.items()):
        srcs = v.get("sources", [])
        lics = sorted({source_license(s, attrib) or "?" for s in srcs})
        A(f"| {d} | {_fmt(v.get('windows', 0))} | "
          f"{_fmt(v.get('documents', 0))} | {_fmt(v.get('tokens', 0))} | "
          f"{', '.join(srcs)} | {', '.join(lics)} |")
    A("")

    A("## Splits")
    A("")
    A("Split on `doc_id`, never `window_id`: windows from one document share "
      "entities, coref chains and topic, so a window-level split leaks. "
      "Stratified by domain, with the 5% targets measured in windows because "
      "that is what training sees.")
    A("")
    A("| split | windows | share | documents |")
    A("|---|---|---|---|")
    for sp, v in (m.get("splits") or {}).items():
        A(f"| {sp} | {_fmt(v.get('windows', 0))} | {v.get('share', 0):.1%} | "
          f"{_fmt(v.get('documents', 0))} |")
    A("")
    A("Exact-duplicate windows are dropped before the split is assigned"
      + (f" ({_fmt(st.get('duplicate_windows_dropped', 0))} dropped)"
         if st.get("duplicate_windows_dropped") else "")
      + ". Splitting on `doc_id` stops a document spanning splits but not two "
        "*different* documents holding identical text, which measured 0.21% of "
        "windows in train and test both (DATASET_SPEC §5.1).")
    A("")
    A("**The `test` split is for corpus QA and ablation only.** Headline "
      "numbers are reported on public gold: training and testing on our own "
      "annotations measures agreement with our annotators, not accuracy.")
    A("")

    A("## Layers and who produced them")
    A("")
    A("| layer | annotator | version |")
    A("|---|---|---|")
    vers = m.get("annotator_versions", {})
    for layer, anns in sorted((m.get("layer_source") or {}).items()):
        for a in (anns if isinstance(anns, list) else [anns]):
            A(f"| {layer} | {a} | {vers.get(a, '?')} |")
    A("")
    A("No layer is silently absent. A layer that could not be produced for a "
      "row carries a mask entry, and an empty value is distinguished from a "
      "missing one — an empty `cls` list means *no dialogue-act function*, "
      "which is a legal annotation, not a gap.")
    A("")

    A("## Known limitations")
    A("")
    lim = []
    if st.get("windows_truncated_by_encoder"):
        lim.append(
            f"**Encoder truncation.** The builder packs to 512 *words*; the "
            f"encoder's limit is 512 *subwords*. "
            f"{_fmt(st['windows_truncated_by_encoder'])} windows carry a tail "
            f"the encoder cannot reach — "
            f"{_fmt(st.get('word_positions_past_encoder', 0))} word positions, "
            f"{st.get('word_positions_past_encoder', 0)/max(tot_t,1):.2%} of the "
            f"corpus. Each row records `n_subword_tokens` and "
            f"`encoder_word_limit`; **training must mask "
            f"`[encoder_word_limit, n_tokens)`** rather than supervise "
            f"positions with no representation.")
    if st.get("dep_sentences_total"):
        r = st.get("dep_sentences_masked", 0) / max(st["dep_sentences_total"], 1)
        lim.append(
            f"**Dependency trees.** {r:.2%} of sentences are not a well-formed "
            f"tree and are masked per token rather than taught. An arc set that "
            f"is not a tree is unusable downstream however accurate its "
            f"individual arcs are.")
    lim.append(
        "**Relations are sparse by inventory, not by failure.** The 96 Wikidata "
        "properties describe encyclopedic facts and most of this corpus is not "
        "encyclopedic. Yield concentrates in news and encyclopedic; windows with "
        "no relation carry a masked layer rather than an empty one, because a "
        "document with no extractable triples is not evidence that none exist. "
        "Bare cardinals and ordinals are excluded from entity sets: NUM appears "
        "in 30 of 85,932 Re-DocRED gold relations (DATASET_SPEC §3A.5e).")
    lim.append(
        "**CLS is thin in places and single-annotator.** `Feedback` is around 2% "
        "of sentences; per-class F1 is reported rather than accuracy alone. "
        "These layers come from one annotator, not the five-family consensus "
        "§4.3 describes.")
    lim.append(
        "**Silver, not gold.** Every layer is model-annotated. NER and DEP "
        "teachers were themselves trained on silver. This corpus is for "
        "training, and is not a benchmark.")
    lim.append(
        "**Junk text survives cleaning** in about 1% of windows: random "
        "base64-like tokens, long URLs, a little lorem ipsum, mostly in the "
        "technical domain.")
    for x in lim:
        A(f"- {x}")
    A("")

    A("## Personal data")
    A("")
    if "business" in doms:
        A("**The business domain is present, which includes the Enron email "
          "corpus — real names, addresses and phone numbers of real people who "
          "did not consent.** DATASET_SPEC §2.2 requires PII detection with "
          "redaction or dropping before any business window is annotated. "
          "Confirm that gate ran before publishing.")
    else:
        A("The business domain is **not** in this build, so the Enron email "
          "corpus — the one source carrying non-consensual personal data about "
          "real people — is absent, and the §2.2 PII gate does not apply. It "
          "becomes a hard blocker if business is added.")
        A("")
        A("Remaining sources are published encyclopedic and news text, public-"
          "domain fiction, documentation, and dialogue datasets. Conversational "
          "sources are predominantly synthetic or Wizard-of-Oz, but they are "
          "not audited for incidental personal data.")
    A("")

    A("## Provenance and reproduction")
    A("")
    A("Each row carries `provenance` naming the annotator per layer and "
      "`loss_mask` recording what must not be supervised. `MANIFEST.json` "
      "records the git sha and a resolved version per annotator — a package "
      "release, or a checkpoint identified by size and mtime so retrained "
      "weights at the same path are distinguishable.")
    A("")
    A("Annotations are cached by content: the item id carries a digest of the "
      "sentence text, so a change to tokenization, cleaning or windowing is a "
      "cache miss rather than a silent mismatch. This is not theoretical — "
      "before content addressing, 29.7% of cached entries had become attached "
      "to different text, and no shape gate detects that (DATASET_SPEC §4.1d).")
    A("")
    A(f"Validated by `v6/gates.py` ({m.get('gates_note', 'see §7')}).")
    A("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()
    mf = OUT / "MANIFEST.json"
    if not mf.exists():
        raise SystemExit(f"no {mf}; run --stage assemble first")
    text = render(json.loads(mf.read_text()))
    if args.stdout:
        print(text)
    else:
        CARD.write_text(text)
        print(f"wrote {CARD} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
